# Generated by Django 5.0.1 on 2024-01-12 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id_alter_eventhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f21909af-c055-4109-824c-209608b67d14'), editable=False, primary_key=True, serialize=False),
        ),
    ]
