# Generated by Django 5.0.1 on 2024-01-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id_alter_eventhistory_id_eventuserfavori'),
        ('events', '0005_alter_event_id'),
    ]

    operations = [
    ]
