# Generated by Django 5.0.1 on 2024-01-24 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_merge_20240120_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('event_number', models.IntegerField()),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
