# Generated by Django 5.0.1 on 2024-01-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='email',
        ),
        migrations.AlterField(
            model_name='game',
            name='avatar',
            field=models.CharField(max_length=500),
        ),
    ]
