# Generated by Django 5.0.1 on 2024-01-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_game_email_alter_game_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
