# Generated by Django 5.0.1 on 2024-01-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
