# Generated by Django 5.0.1 on 2024-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
