# Generated by Django 5.0.2 on 2024-02-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='avatar',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='event_number',
        ),
    ]
