# Generated by Django 5.0.2 on 2024-02-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_event_date_remove_event_time_event_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maximum_place',
            field=models.IntegerField(null=True),
        ),
    ]
