# Generated by Django 5.0.2 on 2024-02-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_avatar_game_url_remove_game_event_number'),
        ('events', '0014_insert_games'),
    ]

    operations = [
    ]
