# Generated by Django 5.0.2 on 2024-02-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_insert_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maximum_place',
            field=models.IntegerField(),
        ),
    ]
