version: '3'
services:
  findmymates:
    image: django
    build:
      context: .
    environment:
      PYTHONPATH: /app/
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - findmymates-network
    container_name: findmymates-django

  database:
    image: mysql
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'findmymates'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - findmymates-network
    container_name: findmymates-mysql

  database-manager:
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - 80:80
    environment:
      PMA_HOST: database
    networks:
      - findmymates-network
    container_name: findmymates-phpmyadmin

volumes:
  database-data:

networks:
  findmymates-network: