version: '3'
services:
  db:
    image: mysql
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'findmymates'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - findmymates-network
    container_name: findmymates-mysql

  db-manager:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      PMA_HOST: db
    networks:
      - findmymates-network
    container_name: findmymates-phpmyadmin

  server:
    image: django
    build:
      context: .
    environment:
      PYTHONPATH: /app/
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - findmymates-network
    depends_on:
      - db
    container_name: findmymates-django

volumes:
  database:

networks:
  findmymates-network: