# Generated by Django 5.0.1 on 2024-01-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('about_me', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
