# Generated by Django 5.0.1 on 2024-01-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
        ('users', '0008_rename_avatar_path_user_avatar_alter_user_password'),
    ]

    operations = [
    ]
