# Generated by Django 5.0.1 on 2024-01-12 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3be4c32a-aeed-4707-8b8a-f810dac148e8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
