# Generated by Django 5.0.1 on 2024-01-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_tag_user_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='users.tag'),
        ),
    ]
