# Generated by Django 5.0.1 on 2024-01-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
